[versions]
agp = "8.8.2"
kotlin = "2.1.0"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
xposed = "82"
yukiApi = "1.2.1"
ksp = "2.1.0-1.0.29"
aliuhook = "main-SNAPSHOT"
libunbound = "1.0.0"
kotlinxSerializationJson = "1.8.0"
kotlinxCoroutinesAndroid = "1.10.1"
ktorClientCore = "3.1.1"
ktorClientCio = "3.1.1"
kotlinReflect = "2.1.20-RC"
kotlinSerialization = "2.1.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
aliuhook = { group = "com.aliucord", name = "Aliuhook", version.ref = "aliuhook" }
xposed = { group = "de.robv.android.xposed", name = "api", version.ref = "xposed" }
yuki-api = { group = "com.highcapable.yukihookapi", name = "api", version.ref = "yukiApi" }
libunbound = { group = "dev.rushii", name = "libunbound", version.ref = "libunbound" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktorClientCore" }
ktor-client-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktorClientCio" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlinReflect" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-serialization = { id= "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinSerialization" }